### ISSUE TITLE
As an author, I want to be able to delete my drafts so that I can declutter my workspace. 

### ISSUE THREAD

**Issue by VirtuaBoza** [tommcgurl/choose-your-own-adventure-builder#19]
Sub-tasks:
Client
- [ ] Add delete button/option on UI
- [x] Add delete draft mutation const
- [x] Add delete draft function to draftService
- [ ] Add delete draft actionType, action creators (do, success, fail), and reducer cases (do, success, fail)

Server
- [x] Add a delete draft GraphQL mutation (verify here that the adventure requested for delete is indeed a draft and has the user listed as an author)
- [x] Add a delete draft repository function
- [x] Add a delete adventure query

**Comment by warpfox** [comment]
Closed by PR #22
