### ISSUE TITLE
As an author, I would like to be able to add choices to a story part.

### ISSUE THREAD

**Issue by tommcgurl** [tommcgurl/choose-your-own-adventure-builder#33]
# Acceptance Criteria

- [x] Author should be able to create a _prompt_ for each set of choices.
     * example: _Would you like to go right or left?_ 
- [x] Author should be able to create choices for their story part that branch to other story parts.
    * example: _go right_ could link to `story-part-right` and _go_left_ could link to `story-part-left`
- [ ] Author should be able to link to a branch ID that has not been created yet.
    * This would allow them to create it at a later point.
    * You could present the author with a dropdown of existing branches as well as an input field to put a new branch id.

**Comment by warpfox** [comment]
I'm going to extract the third bullet point of this one to its own issue and then close this one since 2/3 are good to go
