### ISSUE TITLE
As an author, I need a text editor so that I can write story segments.

### ISSUE THREAD

**Issue by VirtuaBoza** [tommcgurl/choose-your-own-adventure-builder#4]

**Comment by warpfox** [comment]
Let me know what you think about these criteria. This is probably (definitely) not complete or comprehensive.

As an author using the text editor I should be able to:
- [ ] Enter my story text into a textfield
- [ ] Save my text
- [ ] See which branch I'm writing in and give the branch a name
- [ ] See which branch(es) can lead to this one if this isn't the intro/root branch
- [ ] See which branch(es) my current branch is linked to (if they exist yet)
- [ ] Select the branches that each reader choice leads to (if they exist yet)

**Comment by VirtuaBoza** [comment]
I see what you're doing here, but I was trying to write issues as small as each of those bullets. I imagined this issue as equivalent to "Enter my story text into a textfield"

**Comment by VirtuaBoza** [comment]
> Let me know what you think about these criteria. This is probably (definitely) not complete or comprehensive.
> 
> As an author using the text editor I should be able to:
> 
> * [ ]  Enter my story text into a textfield
> * [ ]  Save my text
> * [ ]  See which branch I'm writing in and give the branch a name
> * [ ]  See which branch(es) can lead to this one if this isn't the intro/root branch
> * [ ]  See which branch(es) my current branch is linked to (if they exist yet)
> * [ ]  Select the branches that each reader choice leads to (if they exist yet)

I see what you're doing here, but I was trying to write issues as small as each of those bullets. I imagined this issue as equivalent to "Enter my story text into a textfield"

**Comment by warpfox** [comment]
Welp.

**Comment by VirtuaBoza** [comment]
> Welp.

lol but like.. keep this momentum going and maybe break those bullets into issues if they make sense to you. Or work on this one and add specifics about the text editing stuff... except we'll probably grab an editor from somewhere so idk how much we can be choosers about what the editor does exactly.

**Comment by warpfox** [comment]
Oh yeah? I was thinking we'd probably just literally have an input `<textarea>` inside of a form that we can dress up with some CSS. That way we can have **full control, baby.**

**Comment by VirtuaBoza** [comment]
Well, I hadn't thought of anything except that Tommy posted [these](https://trello.com/c/exxC3SzH/39-wysiwyg-editor-options) on Trello and they seem cool

**Comment by warpfox** [comment]
Okay, yeah, those are pretty dope.
