### ISSUE TITLE
As a reader, I need to be able to turn pages in a story so that I can fucking read, obvs.

### ISSUE THREAD

**Issue by VirtuaBoza** [tommcgurl/choose-your-own-adventure-builder#6]

**Comment by tommcgurl** [comment]
I'm gonna get cracking on this on my flight. I added an example story json that I'm going to go off of for now 👍. I'll make it look like 💩 so that we can come up with some designs together later.

**Comment by VirtuaBoza** [comment]
I see that you pushed against master for this, and it got me thinking that early on it might be good if we all did that for right now instead of having longer living branches so that we can resolve things in smaller pieces. Cuz rn we're gonna be stepping all over each other in these commits i think.
