### ISSUE TITLE
[Editor] Changing the name of the story part breaks the story part editing view

### ISSUE THREAD

**Issue by warpfox** [tommcgurl/choose-your-own-adventure-builder#77]
When you edit the name of the story part and click save, you get a "cannot find property of undefined" error.

I am assuming that since the storyPartKey gets changed but not updated inside the component, it's trying to find the old key that isn't there.

**Comment by VirtuaBoza** [comment]
This is prolly a dupe of #34

**Comment by VirtuaBoza** [comment]
This is a dupe of #34
